### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MERCHANToDEATH** [MineSworn/UltimateArena#101]
Hi, first I love your plugin. I am hoping that you would add the ability to make a class with the items in your inventory using a command, and that it could use crackshot weapons as well. I don't know if this is possible, but I really think crackshot is a much better gun plugin than swornguns. I hope you'll consider this request. Thanks for your time.

**Comment by dmulloy2** [comment]
The logistics of this would be too nightmarish in order to support a plugin I don't use or particularly care for.
