### ISSUE TITLE
[FEATURE REQUEST] - Signs that show Status of Arena minus JOIN capabilities

### ISSUE THREAD

**Issue by Jawakotb** [MineSworn/UltimateArena#102]
Hello!
  I would like to submit the following suggestions for your review:

1) SIGNS FOR ARENA STATUS ONLY -  I would like to submit the idea of having another sign option that instead of allows folks to join the arena, it only shows the current status of the arena without the join capabilities.  This would allow me to add signs at my spawn point to show newly joined folks what mini games are currently active or available.  

2) MESSAGES.YML file -   It would be nice if server owners could have an easier way to tweak the [UA] tag as well as the actual messages that this great plugin offers. (this would also allow for folks to translate to other languages with ease.)

3) Ability to select Circular or Square arena for Spleef (and others if needed). -  While setting up a a few SPLEEF arenas, my server's builders created circular style arenas prior to understanding the 'limitation' in only square restores of the floor.  The idea would be to add a flag that would enable either the '//cyl' command versus the '//set' style of cube generation.

4) Separate ARENA configurations. - Currently all spleef arenas or PVP arenas have the same set death counts and rewards.  I would like to submit that after creating an arena, the server admin could edit the yml file and change the "use default arena configs' to false and then can modify the 'maxdeaths', 'max time for arena', 'time to join', 'rewards' etc.  This came about because we created a 24 player spleef arena that should be two deaths max, but our smaller 4 player spleefs we would like to keep the 3 max death number.  

5) SIGNS THAT SHOW WINNER(s) from last round - It would be great if after an arena has concluded, a leaderboard populates with the players and how they did.  (1st being the winner, 2nd place, etc. etc.  Even if this is the top 3 players only on one sign, would be a GREAT addition!

6) PERMISSION LEVEL ARENAS -  It would be great if folks could only gain access to some arena's based on their rank within the server. (higher ranks get access to higher arenas with greater rewards etc.)

7) HUNGER GAMES AUTO RESET OF CHESTS WITH CONTENTS - My server would utilize the Hungergame arena if the UA plugin would automatically and randomly insert items into chests based on a txt file that listed the items available to that arena.

I know your plate is already full Dan, but I just had to let you know some of the ideas I had that would help make UA greater than it already is.

**Comment by Jawakotb** [comment]
Please ignore #2 as it is a duplicate to some previously submitted requests.  (Sorry)

**Comment by dmulloy2** [comment]
* While 2 is a good idea in theory, it's a pretty tedious task without much upside. I haven't gotten any requests to translate.
* 4 already exists, just set the same options in the arena data file
* Just added 6
* 7 has been planned for some time, but I haven't gotten around to it
* 1, 3, and 5 are possible, but would take some significant recoding

**Comment by Jawakotb** [comment]
HOLY COW DAN!   Thanks for the fast reply!  

I will download the latest build within the next few days and give it a try.  

To clarify more on #4, all I should have to do is open up the individual arena config file (SpleefArena2.yml for example) and add 'maxdeath: 3' right below the 'max player' entry? I am assuming all other available options would follow suite right below there as well.)

I only wish all plugin devs were as fast and responsive as you....THANK YOU!

**Comment by GarretSidzaka** [comment]
Unfortunately, there can only be one Dmulloy2.  He is by far the coolest
dev out there.
