### ISSUE TITLE
Defining Min/Max players?

### ISSUE THREAD

**Issue by draksterau** [MineSworn/UltimateArena#105]
Hi Mate,

Im having trouble defining the minimum players and maximum players for arenas, as I want arenas between 2-8 players, not the default 24.

Can you help me out ?

**Comment by dmulloy2** [comment]
Just set ````maxPlayers: 8```` in the arena.dat file.

**Comment by draksterau** [comment]
What about minimum players man? if I have an arena that 2 is really not enough for?

**Comment by draksterau** [comment]
@dmulloy2 Thanks man, Appreciated :)
