### ISSUE TITLE
arenas reset to 0 players

### ISSUE THREAD

**Issue by Jawakotb** [MineSworn/UltimateArena#108]
Dan,
  After putting into place the latest DEV build of UA, the one that adds "max and minplayers' to the dat file, all of my current arenas show 0 max players on all signs and noone can join.  Upon looking into the arena dat files, it appears the new build 'removes' the maxplayer line from the dat file upon a server restart.

I sure hope not, but do I need to redo all my arenas with the new configuration process or what does the new arena dat files look like so I can amend my current ones with the required entries.

Thank you in advance.

**Comment by dmulloy2** [comment]
Should be fixed in https://github.com/MineSworn/UltimateArena/commit/2b2e76072fe1cf5972cbc58c2570144c3ea45ac6.

If the .dat files were changed, you just have to add ````maxPlayers: [max players]```` to the file.

**Comment by Jawakotb** [comment]
I have attempted that but upon restarting the server, the lines are removed.  (It is odd)

**Comment by Jawakotb** [comment]
Here is pastebin from one of my CTF arenas (Before and After Reboot)

http://pastebin.com/BS67D01G

**Comment by dmulloy2** [comment]
Are you using build 704?

**Comment by Jawakotb** [comment]
I am not!   (Duh!)  699 is what I have....<<runs off to download new JAR>>
