### ISSUE TITLE
Some more errors.

### ISSUE THREAD

**Issue by Zilacon** [MineSworn/UltimateArena#109]
Build #702
Server: MCPC+ 1.6.4 Build 272
Error message in chat: http://prntscr.com/6ppe6b
Error message in console:
````
04-04 18:41:08 [SEVERE] [UltimateArena] Encountered an exception while adding Civility to arena KingOfTheHill: java.lang.IllegalArgumentException: x cannot be negative!
Affected classes:
 org.apache.commons.lang.Validate.isTrue(Line 136) [Validate.class]
 net.dmulloy2.ultimatearena.util.Util.random(Line 201) [UltimateArena.jar]
 net.dmulloy2.ultimatearena.UltimateArena.kickRandomPlayer(Line 929) [UltimateArena.jar]
 net.dmulloy2.ultimatearena.UltimateArena.addPlayer(Line 882) [UltimateArena.jar]
 net.dmulloy2.ultimatearena.tasks.ArenaJoinTask.run(Line 45) [UltimateArena.jar]
 net.dmulloy2.ultimatearena.UltimateArena.attemptJoin(Line 839) [UltimateArena.jar]
 net.dmulloy2.ultimatearena.UltimateArena.attemptJoin(Line 736) [UltimateArena.jar]
 net.dmulloy2.ultimatearena.commands.CmdJoin.perform(Line 44) [UltimateArena.jar]
 net.dmulloy2.ultimatearena.commands.Command.execute(Line 140) [UltimateArena.jar]
 net.dmulloy2.ultimatearena.handlers.CommandHandler.onCommand(Line 181) [UltimateArena.jar]
 org.bukkit.command.PluginCommand.execute(Line 44) [PluginCommand.class]
 org.bukkit.command.SimpleCommandMap.dispatch(Line 192) [SimpleCommandMap.class]
 org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(Line 533) [CraftServer.class]
````

**Comment by Petpeeve** [comment]
^
I just created a simple King of the Hill arena, followed all the steps, and only the creator of the arena can join it. It will say something along the lines of "Civility has created a King of the Hill arena 0/1 players" I don't remember the exact message, and from there anyone who uses /ua join KingOfTheHill it will say "Failed to add you to the arena! Contact an Administrator!" http://prntscr.com/6ppgq1

**Comment by dmulloy2** [comment]
This is an unexpected consequence of https://github.com/MineSworn/UltimateArena/commit/cac789ea3042993f65640f0cbe682a3af740c173.

This has been fixed in build 704, but you may have to manually add ````maxPlayers: [max players]```` in the arena data files.
