### ISSUE TITLE
Error on Creating MobArena in Console

### ISSUE THREAD

**Issue by Lucas502** [MineSworn/UltimateArena#110]
http://pastebin.com/JN4SR8sj
Arena doesn't create, it says this in console.
Also ingame it says "Creation of (Arena Name) failed. Check Console!"

**Comment by Lucas502** [comment]
Please comment a solution soon.

**Comment by GarretSidzaka** [comment]
We do not receive any money or other compensation for these softwares, which we provide with no warranty, for absolutely free.  I expect our users to understand this and not impatiently post to us.  Both myself and the lead developer have full-time obligations, and minecraft factors quite small in them.  While we are glad you are making lots of money on your server, we are not.

**Comment by dmulloy2** [comment]
You're using a fairly outdated build. Grab a newer one here: http://ci.shadowvolt.com/job/UltimateArena/

**Comment by Lucas502** [comment]
To Garret,

Hi, im Lucas. I would like say that I have no idea what you are talking of. I earn no compensation for my server, I never said that or even got close to it. I don't understand where that idea came from. 

                                                          - Lucas

**Comment by GarretSidzaka** [comment]
I'm referring to your deleted comment rushing dmu, who has full time obligations.
