### ISSUE TITLE
Bomb Arena automatically creating Stone Catastrophes?

### ISSUE THREAD

**Issue by Petpeeve** [MineSworn/UltimateArena#111]
Good Evening!

I'm working on a bomb arena for my network and I have gotten the buildings perfectly laid out and set up and convincing bombs built already. Upon starting the arena, it creates a horrible stone structure which I assume is a bomb, but it looks nothing of the sorts. I'm just wondering if there's any possible way to disable it from automatically creating this structure and just using a radius around my already built bombs to determine where the bomb is, if that makes any sense. Below is a screenshot of the creation the plugin makes. As you can see the bottom part is clipping through the floor creating an eyesore for my players and the top bit is just a piece of floating wool, also distracting and making the environment less convincing overall. http://prntscr.com/6uomai http://prntscr.com/6uomq3

If you could guide me in the right direction or give me any advice on how to resolve this small problem I would be incredibly thankful!

Warm Regards,
Petpeeve

**Comment by dmulloy2** [comment]
This is a really old feature from the original author.  It has its merits as an identifier for flags (bombs, ctf flags, etc), as it usually shows the owning team.  I agree that it's an eyesore, but I'm not totally sure how exactly to fix it.  I'd be open to suggestions, though.

**Comment by dmulloy2** [comment]
Any more info on this?
