### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by KeithSt0ne** [MineSworn/UltimateArena#112]
-Ability to set what classes each team has access to

We do a Star Wars themed conquest mode and both sides are supposed to have their own set of classes.

-Rotating maps, allow us to create a group and the maps in that group rotate, when one ends the next one starts.

We allow always join even while matches are going, this would help with players getting spread out between multiple maps.

-We need the option to join a match already in progress.

**Comment by dmulloy2** [comment]
#2 would be too difficult to implement and I really don't have a use for it.
