### ISSUE TITLE
Whenever I join any lobby, it makes me stuck in the air and kicks me for flying

### ISSUE THREAD

**Issue by Fang86** [MineSworn/UltimateArena#113]
I made lots of space in the lobby making sure it didn't spawn you in block, which it doesn't, but nobody can join the lobby because you just get kicked for flying 5 seconds after you join it.

**Comment by dmulloy2** [comment]
What version of UltimateArena are you using?

**Comment by dmulloy2** [comment]
Closed due to lack of information.
