### ISSUE TITLE
Factions

### ISSUE THREAD

**Issue by N0LEJ** [MineSworn/UltimateArena#114]
Hey, N0LEJ here. I am just reporting to tell you a bunch of glitches and bugs that need fixing.
1) ./f perm is ruined. If I (for example) give a player the perm ./f perm p TESTSUBJECT build allow, it will then deny them access to ./f per p TESTSUBJET break allow and vice versa. So if you can break, you cannot build, if you cannot build you can break and so forth. 

2) In order to build in someone's faction, they have to be ranked "co-admin" and that can be troublesome. Or, alternatively, you make the mod and add a bunch of faulty perms to them.

For now, that's all I can think of. If anything else comes up I will tell you.

**Comment by dmulloy2** [comment]
UltimateArena isn't factions.
