### ISSUE TITLE
Can't Change default  class for diffrent Games

### ISSUE THREAD

**Issue by Aaron211997** [MineSworn/UltimateArena#117]
So i have multiple Arenas like Spleef, CTF, PvP And i am having the same issue with all of them I am not able to change the default class in the arena .dat files and when i do and restart the server. They revert back to archer. Can anyone help me with this issue thank you. here is the file
type: spleef
world: minigames
lobby1:
  x: -1066
  z: -209
lobby2:
  x: -1090
  z: -242
arena1:
  x: -1049
  z: -204
arena2:
  x: -1094
  z: -263
lobbyRed:
  x: -1078
  y: 23
  z: -226
specialType: SNOW_BLOCK
flags:
  '0':
    x: -1090
    y: 23
    z: -242
  '1':
    x: -1066
    y: 7
    z: -209
  '2':
    x: -1066
    y: 4
    z: -209
  '3':
    x: -1090
    y: 2
    z: -242
liked: 0
played: 0
maxPlayers: 24
defaultClass: archer

**Comment by dmulloy2** [comment]
The arena files are saved when the sever stops. You can either stop the server then edit or use /ua reload
