### ISSUE TITLE
Default kits

### ISSUE THREAD

**Issue by xxHyperSonicMC** [MineSworn/UltimateArena#118]
Ok so i try to do king of the hill, but it automatically defaults to the archer kit, and i created my own king of the hill kit that i want it to default to. Is there a way i can do that?

**Comment by dmulloy2** [comment]
Which version of UltimateArena are you using?

**Comment by xxHyperSonicMC** [comment]
I am using the version 2.7 and I also solved the problem in the arenas
folder there are .dat files if you open them with notepad++ u can edit the
default class.

**Comment by dmulloy2** [comment]
Yeah that's what I was going to suggest.
