### ISSUE TITLE
Expand on API

### ISSUE THREAD

**Issue by Log1x** [MineSworn/UltimateArena#121]
Was curious if you could expand on the API a little bit to get things as current/max players in an arena, arena status, etc. so we could get somebody like extended_clip to add placeholders into [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) for use in such things as [CustomGUI](https://www.spigotmc.org/resources/customgui.7386/)

Below is a screenshot example where this could be really awesome if the placeholders were there:
![screenshot](http://log1x.com/screenshots/2015-08-14_01-11-44_CHJA3.png)

Another use is being able to have arena placeholders in things such as Holographic Displays which if extended_clip will add the placeholders to PlaceholderAPI, can be achieved with [PlaceholderInjector](https://www.spigotmc.org/resources/placeholderinjector.10022/).

Sorry for the recent feature requests, I really love UltimateArenas! It's the first high-performance Arena plugin that is open source and I've been able to tweak to work flawlessly on my Multiverse server.

Thanks a ton.

**Comment by dmulloy2** [comment]
The necessary APIs exist, but I guess they aren't properly documented.  I'm more than happy to fix that though.

**Comment by Log1x** [comment]
That'd be great! :)

http://pastie.org/pastes/10351773/text?key=us8rgzvjsgrwurkpq4tsw would love to have some arena-name specific placeholders into PlaceholderAPI so the examples above are more possible.

%ua_ARENANAME_players% (ex. 1)
%ua_ARENANAME_maxplayers% (ex. 24)
%ua_ARENANAME_status% (ex. IN-PROGRESS)
%ua_ARENANAME_type% (ex. FFA)

Time left is also another possibility, I suppose. :o 

I don't see a whole lot of action on the tracker here, so sorry if I'm raising the dead here posting issues for UltimateArena, but it's easily the best and most well written Arena I've come across with multiverse/worldedit support. :100: 

I'm a tad newer to Java but once you do scoreboard, I could take the plunge and add a lang file for localization maybe? Right now I just recompile it with my color/chat changes. I also added support for TitleManager for titles when arena's start, etc. but I'm pretty sure a lot of the customizations I've done isn't the "perfect" way to do it so I haven't really pushed anything to GitHub and am more so tinkering/learning.

Thanks a ton!

**Comment by KitCatMC** [comment]
This would be SO awesome!

**Comment by dmulloy2** [comment]
The API should be good, the scoreboard is done, and I'll be doing the localization / messages customization in the coming days.
