### ISSUE TITLE
Command List

### ISSUE THREAD

**Issue by veteranmina** [MineSworn/UltimateArena#122]
Not a plugin issue per-say, but this is the only way I could find a good way to contact you.

I am currently setting up your plugin on my server, and creating the game is perfectly fine, but I do wish that we could get a full command list that this plugin provides with arguments to the commands as well.

Thanks!
Veteranmina

**Comment by dmulloy2** [comment]
````/ua help```` is what you're looking for. It shows a list of commands you can use, what they do, and what their arguments are.

**Comment by veteranmina** [comment]
Please reopen this, as I am trying to figure out your commands for /ua option <type> <name> <option> <value> and other commands that have arguments. Your command list here is not completed, and has stated that for some time now.  http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/commands/

Thanks!

Veteranmina

**Comment by GarretSidzaka** [comment]
for now a quick fix to this is to make a copy of the plugin on your
desktop, or in linux extract it to your home folder.  then read the
contents of a file called "plugin.yml" and any other text readable files
you can find inside of that jar file.

**Comment by veteranmina** [comment]
I have looked, I am wanting to know what the arguments are for /ua option. 
I really want to use this plugin, and for others for simplicity rather than having to open your plugin scouring everywhere to find the arguments for this. I'm just wanting to use your plugin.

**Comment by dmulloy2** [comment]
/ua option basically just changes the configuration. I haven't fully implemented it properly yet, but you can find the source (and by extension the arguments) here: https://github.com/MineSworn/UltimateArena/blob/master/src/main/java/net/dmulloy2/ultimatearena/commands/CmdOption.java
