### ISSUE TITLE
Arena's not saving to .yml

### ISSUE THREAD

**Issue by veteranmina** [MineSworn/UltimateArena#124]
When loading the plugin, it does not load the arena's but gives this error:

8:48:52 PM CONSOLE: WARN]: [UltimateArena] Encountered an exception while loading arena Storm.dat: org.bukkit.configuration.InvalidConfigurationException: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
8:48:52 PM CONSOLE: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
8:48:52 PM CONSOLE: java.lang.IllegalArgumentException: Specified class does not exist (net.dmulloy2.ArenaLocation)

**Comment by dmulloy2** [comment]
What version of UA are you using?

**Comment by veteranmina** [comment]
I tried using the August 29th build #747. After the server restarts UltimateArena would not save it's configurations. During the time the arena is setup it is playable but no configs are written.

**Comment by veteranmina** [comment]
Also we are using Spigot CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by dmulloy2** [comment]
In order for arena.dat configuration changes to persist, you have to either use /ua reload or completely stop the server before editing them.
