### ISSUE TITLE
Signs don't refresh

### ISSUE THREAD

**Issue by KitCatMC** [MineSworn/UltimateArena#125]
Signs don't refresh, when I make one it says ''JOIN'' in green with ''0/20'' players.
When I played 1 time there is ''STOPPING" in yellow and ''0/24''.
It won't refresh and stay at this until I rejoin the next day.
When I join a game with ''STOPPING'' ''0/24'' it looks like it changed the config because there is now really place for 24 players instead 20 what I configured.

Does somebody know how to solve this?
(I have the latest version of either the plugin, java and spigot)

**Comment by dmulloy2** [comment]
Are you using 2.x or 3.0?

**Comment by KitCatMC** [comment]
2.7 I couldn't find a newer version and wouldn't risc the development versions.

**Comment by KitCatMC** [comment]
I downloaded the latest Development Build and the problem is still there..

**Comment by dmulloy2** [comment]
What does your signs.yml look like?

**Comment by KitCatMC** [comment]
The problem isn't there anymore. I just had to restart the server and remake the sign.. :/
Thanks for your help tho! ;D
