### ISSUE TITLE
Default Killstreak Removal

### ISSUE THREAD

**Issue by YepImRobbie** [MineSworn/UltimateArena#126]
How do I remove the default kill-streaks?

I've also contacted you via email regarding something else.

**Comment by dmulloy2** [comment]
You would set ````killStreaks:```` without any content in the appropriate config. 

I got and responded to your email.

**Comment by YepImRobbie** [comment]
Thanks, also got back to you on the email. :)

**Comment by YepImRobbie** [comment]
Sorry, I'm slightly confused by "appropriate config." I've put this in the arena file and config file, pvpConfig, and it still doesn't work. :[

**Comment by dmulloy2** [comment]
It should work regardless of the level, what does the arena file look like?
