### ISSUE TITLE
Problems with new messages system

### ISSUE THREAD

**Issue by YepImRobbie** [MineSworn/UltimateArena#127]
Hi Dan,

I tested the Build #754 (Sep 26, 2015 2:44:16 PM)
UltimateArena version 3.0-SNAPSHOT-b754
Spigot 1.8.8 version git-Spigot-76236cb-62a2169 (MC: 1.8.8) (Implemeneting API version 1.8.8-R0.1-SNAPSHOT)

I've run into a few problems:
1. Prefix does not recognise formatting codes
2. Joining the arena does not work

In-game error output (Demonstrates [1, 2]): http://imgur.com/4MtvE0s
Console Error: http://pastebin.com/fM2eTAVg

Hope this is a comprehensive report. If there is any information just give us a shout and I'll get round to delivering the necessary information.

**Comment by dmulloy2** [comment]
Those two issues should be fixed in https://github.com/MineSworn/UltimateArena/commit/d931d23def210599a9a199116b74355e034a1e25

**Comment by YepImRobbie** [comment]
Can confirm.

Any way to disable the scoreboard so it doesn't conflict with the FeatherBoard plugin?
