### ISSUE TITLE
lobbyTime broken w/ pvpConfig.yml

### ISSUE THREAD

**Issue by YepImRobbie** [MineSworn/UltimateArena#129]
# Main Configuration for the PvP Arena Type
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/

gameTime: 240
lobbyTime: 10
maxDeaths: 5
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: false
cashReward: 0
rewards:
killStreaks:
  60:
    - item,heyhacker,46,1

Lobby time is always 85 regardless of changing it.

**Comment by YepImRobbie** [comment]
I think defaultClass is also still not working, I have spaces in the kit's name, that might be why? I put defaultClass: 'LEVEL 01 KIT' in the nuketown.dat file.

**Comment by YepImRobbie** [comment]
Arena time integer is not being recognised either

**Comment by YepImRobbie** [comment]
Blank message shown if concluded message is removed

**Comment by YepImRobbie** [comment]
Blank message shown for join arena please wait message if removed

**Comment by YepImRobbie** [comment]
No way to get rid of null team won the match at map message

**Comment by YepImRobbie** [comment]
Looks like killStreaks stopped working too, I'm getting strength potions again.

**Comment by dmulloy2** [comment]
Can't reproduce any of the configuration stuff, seems to be working fine.

**Comment by YepImRobbie** [comment]
Ok, using the latest jar I deleted UA's folder, and regenerated it. Configs do not generate, and that would seem to explain as of why killStreaks, gameTime and lobbyTime integers were not being read?

**Comment by dmulloy2** [comment]
Type configs are located at /UltimateArena/types/<type>/config.yml. I guess I forgot to delete the old ones, but that should be fixed as of the latest commit.

**Comment by YepImRobbie** [comment]
permissionNode: ''

Is wiped from the class files, unless you changed how permission nodes are stated.

**Comment by dmulloy2** [comment]
Specifying permission nodes was always a bit clunky and didn't always work, so I replaced it with ````needsPermission: true/false````. The format for permission nodes is ````ultimatearena.class.[class name lower case]````.

**Comment by YepImRobbie** [comment]
Dan, if a class has spaces in the name is it recognised as an underscore?
