### ISSUE TITLE
Configs

### ISSUE THREAD

**Issue by FlyingSquidwolf** [MineSworn/UltimateArena#131]
Hey,

it is unclear how exactly the configs for kill streaks and such are setup. What file do they go in? Or do they go in the folder? If they go in the folder how does one name the folder and set out the file to apply to a certain arena etc.

**Comment by dmulloy2** [comment]
Yeah I realize it's pretty unclear, so I've been working on a wiki page for it: https://github.com/MineSworn/UltimateArena/wiki/Configuration

But basically the killstreaks are a configuration section in the proper config file (type config or arena config), the format can be found above.
