### ISSUE TITLE
Spectator

### ISSUE THREAD

**Issue by YepImRobbie** [MineSworn/UltimateArena#133]
Hey dan,

Can't seem to find anyway to configure the spectate mode? Could you clarify if it's possible?

If it isn't possible, then a config for spectate mode would be greatly appreciated, especially if we can say whether we want them to be invisible and whether we want them to fly.

Thanks.

**Comment by dmulloy2** [comment]
Spectator mode is currently not configurable. I can add that soon, but I was planning to just convert to using Minecraft's inbuilt spectator mode.
