### ISSUE TITLE
Arena Creation Error

### ISSUE THREAD

**Issue by elian1203** [MineSworn/UltimateArena#135]
Hello, I have checked out your plugin and it looks pretty good, though I am having trouble upon creation of an arena. Whenever I do so, it will say "Creation of arena ffa failed. Check console! And the error is telling me something about the world cannot be null. I have no idea why the world would be null. Here is the full error code:
[16:27:30] [Server thread/INFO]: Elian issued server command: /ua sp done
[16:27:30] [Server thread/ERROR]: [UltimateArena] Encountered an exception while saving Arena: ffa:
java.lang.NullPointerException: null
Affected classes: 
	net.dmulloy2.ultimatearena.handlers.FileHandler.save(FileHandler.java:54)
	net.dmulloy2.ultimatearena.types.ArenaZone.save(ArenaZone.java:136)
	net.dmulloy2.ultimatearena.creation.ArenaCreator.complete(ArenaCreator.java:119)
	net.dmulloy2.ultimatearena.creation.ArenaCreator.stepUp(ArenaCreator.java:83)
	net.dmulloy2.ultimatearena.creation.FFACreator.setPoint(FFACreator.java:187)
	net.dmulloy2.ultimatearena.UltimateArena.setPoint(UltimateArena.java:1167)
	net.dmulloy2.ultimatearena.commands.CmdSetPoint.perform(CmdSetPoint.java:27)
	net.dmulloy2.ultimatearena.commands.UltimateArenaCommand.execute(UltimateArenaCommand.java:92)
	net.dmulloy2.ultimatearena.handlers.CommandHandler.onCommand(CommandHandler.java:73)
[16:27:30] [Server thread/ERROR]: [UltimateArena] Could not load Arena ffa: World cannot be null!

**Comment by dmulloy2** [comment]
Use the latest development build, this was fixed a while ago.
