### ISSUE TITLE
Red always wins PvP mode

### ISSUE THREAD

**Issue by 2001zhaozhao** [MineSworn/UltimateArena#136]
Hi, in my server the Red team always wins PvP(team deathmatch) mode except when the whole Red team quits, in which case Blue will win. I have also noticed that neither of the teams get rewards if PvP ends without one of the team all quitting. However the rewards are given normally if one of the teams quit and the other wins.

**Comment by dmulloy2** [comment]
What version of UA are you using?

**Comment by 2001zhaozhao** [comment]
Newest Dev build

**Comment by dmulloy2** [comment]
That's really weird. I'll look into it tomorrow.

**Comment by MatteCarra** [comment]
It seems fixed

**Comment by 2001zhaozhao** [comment]
Thank you!
