### ISSUE TITLE
Could you add joining after the game starts?

### ISSUE THREAD

**Issue by 2001zhaozhao** [MineSworn/UltimateArena#137]
Hi, it seems that I couldn't find an option to let players join after the game has already started. I have games where players have infinite lives, and I wish to have more players in an arena, so I would really like players to be able to join (and spawn in the game) after the game has already started.

**Comment by dmulloy2** [comment]
https://github.com/MineSworn/UltimateArena/wiki/Configuration#configuration-options

Set joinInProgress to true in the applicable configs.

**Comment by 2001zhaozhao** [comment]
Doesn't seem to work.
My config:

# Main configuration file for the pvp arena type
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/

gameTime: 300
lobbyTime: 60
maxDeaths: 999
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: true
cashReward: 20
rewards:
- GOLD_NUGGET, 3
joinInProgress: true
mandatedClasses:
  red: "Player"
  blue: "Player"

When I try to join in-game it still says "This arena has already started!"
