### ISSUE TITLE
Teleporation on arena end doesnt work properly

### ISSUE THREAD

**Issue by DraksterAU** [MineSworn/UltimateArena#139]
Players on my server are randomly being teleported back to the arena when the arena ends, especially when its a close game and things are closely tied til seconds before.

To be clear, the teleport bug happens MORE often the closer the game, but happens for 1 in perhaps 5 games otherwise.

PVP Type, with minPlayers and maxPlayers set (nothing else is non-standard)

**Comment by dmulloy2** [comment]
What version of UA are you using?

**Comment by DraksterAU** [comment]
3.0 Snapshot b704.. Last one I can get working on 1.7.10 Cauldron

**Comment by dmulloy2** [comment]
Use the latest dev build and report any errors you get with it.

**Comment by DraksterAU** [comment]
This occurs because of bugs in KCauldron (new build fixed it)
