### ISSUE TITLE
Joining arena in game causes arena to not stop properly

### ISSUE THREAD

**Issue by 2001zhaozhao** [MineSworn/UltimateArena#140]
Hi, although joining an arena in game now works, if a player joined when the arena is in game, the arena will only work properly until the end of the match. Then the plugin seems to fail making the players who joined mid-game leave, making them stuck in the arena. When trying to join, it says "this arena is stopping!" Even if every stuck player manually leaves via the leave command, it still says the arena is stopping. After /ua disable <name> then /ua enable <name> the arena still says it's stopping. /ua info <name> correctly shows information of the match about the stuck players. The arena basically goes on stopping forever after the first match after the plugin is loaded. Reloading the plugin's config doesn't even seem to help.

My custom plugin sets scoreboards of players in UA to a custom scoreboard in order to hide name tags of enemies. I do not know if this is related to the bug, but probably not. The custom plugin also has a listener of UA's join and leave events mainly to give players items in-game, and provide money kill awards, but the listener never modifies any aspects of UltimateArena values.

**Comment by 2001zhaozhao** [comment]
I'm using the newest development version

**Comment by dmulloy2** [comment]
In the future, please provide errors that arise when stuff like this happens.

I did some testing myself and came across this error: http://pastebin.com/Dd4Zy8R3 which would explain the strange behavior.
