### ISSUE TITLE
null team always win the PvP arena .-.

### ISSUE THREAD

**Issue by 2001zhaozhao** [MineSworn/UltimateArena#142]
Yeah, after the red team always win fix, I noticed that "null team won the arena of (insert arena name)" always come up when the game ends. The "null" is yellow in color like the rest of the message. Haven't tested what happens when one of the teams all quit though.

**Comment by dmulloy2** [comment]
The only instance I can reproduce this in is when the arena ends due to not enough people joining.

**Comment by 2001zhaozhao** [comment]
This is what happens here...
![2015-12-29_10 15 43](https://cloud.githubusercontent.com/assets/15002454/12036581/45f88564-ae15-11e5-8185-e4bf2af8f814.png)
![2015-12-29_10 15 35](https://cloud.githubusercontent.com/assets/15002454/12036582/45fc6440-ae15-11e5-8485-134f93e1e775.png)
(As you can see the blue team is spawnkilling the red team, they should have won)
And then null wins.
![2015-12-29_10 15 37](https://cloud.githubusercontent.com/assets/15002454/12036583/45fdf53a-ae15-11e5-81cd-54670fd565ab.png)

Config file for mode:
[config.txt](https://github.com/MineSworn/UltimateArena/files/74056/config.txt)

I never changed any per-arena settings, and the arena itself was created in Build 782. (I am using newest Build 783)
