### ISSUE TITLE
Configurable win condition

### ISSUE THREAD

**Issue by 2001zhaozhao** [MineSworn/UltimateArena#143]
Hi, in my server FFA always ends with a message saying "Time ran out! Game over!" but nobody is winning the arena. I am using the latest dev build and the error only seems to be happening on it. However, I have the win condition set to be most kills. I set the arena to have infinite respawns and I have turned the scoreboard option off. There aren't any errors in console when the message is shown.

**Comment by dmulloy2** [comment]
This isn't an error, it's the current intended behavior.

**Comment by 2001zhaozhao** [comment]
Well, it's weird since my win condition is set to "most kills" instead of anything else like "last man standing", so the player with the most kills is supposed to win.

**Comment by dmulloy2** [comment]
I don't believe there's currently a win condition, but the more I think about it that would be a good idea.
