### ISSUE TITLE
"ua done" didn't working on Spigot 1.7.10

### ISSUE THREAD

**Issue by Saintmare** [MineSworn/UltimateArena#145]
I'm VERY bad in English, excuse me.
When I type "/ua done" into the chat, i get 
"Unknown UltimateArena command "done". Try /ua help!"
What's this?

**Comment by dmulloy2** [comment]
It was replaced with /ua sp done

**Comment by Saintmare** [comment]
Oh, thanks! Can you write about this on BukkitDev, page "Creating Arenas"?

**Comment by dmulloy2** [comment]
Yeah, I probably should update BukkitDev
