### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by AwakenedRage98** [MineSworn/UltimateArena#146]
Hi,

I made a spleef Arena, and I keep getting the following error thrown:
You can see the logs here: http://pastebin.com/vHTDErQQ

I was completely unaware whether I had to set 2 points for the spleef Arena. I marked the selection using WorldEdit which the players are supposed to destroy and used the same selection twice (since I dint know that it was asking for 2 separate points. 

I am confused as to why its not allowing them to destroy the designated area. Is this a bug or is this an error made by me. 

I would try looking farther if I had more knowledge of Java, but I'm more of a C# and Python Programmer then anything.  

I know for a fact that Players are able to damage each other during the match and that it may be possibly referring to Entities trying to damage blocks. But I am not that familiar with Minecrafts API either. 

Thanks for your time,

**Comment by dmulloy2** [comment]
This is an issue that has to do with the changes in 1.9. I'll push a fix soon.
