### ISSUE TITLE
Feature Request: Singleplayer arenas

### ISSUE THREAD

**Issue by Sharrq** [MineSworn/UltimateArena#148]
Would it be possible to add singleplayer type arenas like Parkour courses and such? Minigames (the plugin) accomplishes this by just having a sign you click at the end of the parkour to complete it.

The only other thing that would be important for singleplayer arenas would be to set a reward for completing it the first time, and then a secondary reward for repeating it.

**Comment by dmulloy2** [comment]
You can set the arenas to have a maximum of 1 player, but there currently isn't a way to add diminishing rewards.
