### ISSUE TITLE
forceRespawn not working on spigot 1.9

### ISSUE THREAD

**Issue by mcCURS0R** [MineSworn/UltimateArena#150]
forceRespawn is not working as i respawn somewhere in th world and get teleported back to the arena after 2 or 3 seconds

 i've user the protocolLib.jar from: https://www.spigotmc.org/resources/protocollib.1997/

**Comment by dmulloy2** [comment]
Use the latest development builds from my Jenkins server and let me know if it's fixed.

http://ci.dmulloy2.net/job/ProtocolLib/
http://ci.dmulloy2.net/job/UltimateArena/

**Comment by dmulloy2** [comment]
Should be fixed in the latest build, there was an issue with the dependency provider.
