### ISSUE TITLE
Custom NPCs support

### ISSUE THREAD

**Issue by DraksterAU** [MineSworn/UltimateArena#151]
Hi There,

Can you please make "CUSTOMNPCS_CUSTOMNPC" a persistant Entity type in the official builds?
This will allow for Cauldron servers to use Modded NPCs in their arenas, which removes the need for signs, or they could alternatively have them as either friendly or enemy npcs in the arenas.

Presently they are destroyed on arena completion - I've created a custom build for now for my server.

- Bysokar

**Comment by dmulloy2** [comment]
Not entirely sure if or how this would be implemented.

**Comment by DraksterAU** [comment]
If this is true, don't remove the entity on arena completion:
entity.getType().name().equals("CUSTOMNPCS_CUSTOMNPC").

**Comment by DraksterAU** [comment]
Types are a bit odd with a hybrid server. Referencing it by its type would break in normal bukkit I think. hence the string comparison. Not sure if you can implement better.

**Comment by DraksterAU** [comment]
Thanks man :D
