### ISSUE TITLE
FEATURE REQUEST RANKING SCOREBOARDS SIGN SCOREBOARD

### ISSUE THREAD

**Issue by RAZERMC** [MineSworn/UltimateArena#154]
Please add a ranking system separately for each minigames  with sign whose the top player on this minigame 
example sign
===============
     [USINE]
minigamename
===============    

and will output this

SPLEEF RANKS
1. name
2. name
3. name

and if you put a sign beneath it. it will update the sign too to

4. name
5. name
6. name
7. name

it will motivate the players to win more as they will see the their names on boards
thanks and more support

**Comment by dmulloy2** [comment]
This already exists, just make a sign like this: ````[Last <Arena>]````
