### ISSUE TITLE
Players cannot move in the lobby

### ISSUE THREAD

**Issue by RAZERMC** [MineSworn/UltimateArena#155]
When a player teleports to lobby. the player is always 1 block higher than the set spawn point and cannot move.

They always gets kicked by nocheatplus as fly cheat

My work around for this is set 1 block hole in the ground step inside the hole set the spawn point then get out of the hole then patch the hole with a new block.

The problem with this is the players still cant move.

Im using spigot 1.10 latest build tools on java 8 upon posting this.

**Comment by dmulloy2** [comment]
They're one block higher by design, for some reason I don't remember at this point. Unless your lobby is 2 blocks high, I can't see this causing an issue.
