### ISSUE TITLE
How do i edit Classes?

### ISSUE THREAD

**Issue by Rheise517** [MineSworn/UltimateArena#156]
Hello!
Today, i got the UltimateArena plugin, and i made a mob game. But we want guns, but the sniper class only has 1 ammo for the sniper, how do i edit that? And for all the classes

**Comment by GarretSidzaka** [comment]
hello, 

look in your plugins folder inside of the server.  in there is an UltimateArena folder.  Inside of that folder are many different things you can edit, including classes!

enjoy!

**Comment by Rheise517** [comment]
There is no file in the UltimateArenas folder for classes, I checked
through all of the folders.

**Comment by GarretSidzaka** [comment]
In my ultimatearena folder there is a classes folder.  inside are yml files that are the individual classes.  if those folders are not auto-generating this might be a valid issue for dmu

**Comment by dmulloy2** [comment]
If it's not working, try the 3.0 dev builds. I've been meaning to release it for some time but I haven't gotten around to it.
