### ISSUE TITLE
Grace Period

### ISSUE THREAD

**Issue by dmulloy2** [MineSworn/UltimateArena#158]
New feature idea: possibly adding a grace period after a player respawns so they don't get spawn killed. It would be broken after x amount of seconds or when they start attacking, similar to how Smash Bros does it.

**Comment by GarretSidzaka** [comment]
Thats a really good idea.   You could use particle effects to denote it.
You would probably need to make it very short or otherwise make it so they
cant attack during it

**Comment by dmulloy2** [comment]
Yeah I figure it'd be configurable with the default being a few seconds.
