### ISSUE TITLE
Executable Kit Contents

### ISSUE THREAD

**Issue by Kevin61630** [MineSworn/UltimateArena#159]
So for the in-game kit contents, I'm wondering if they can be executed by console. For example:

kit_contents:
- /give @p diamondsword 1 sharpness:1 unbreaking:1
- /give @p steak 12 name:&eThis_&dis_&aa_&btest
- /give @p paper 1 name:&6Good_luck! lore:&d&oYou'll_need_it

Please add this as soon as you can. I'm using your plugin and my server releases soon.

**Comment by dmulloy2** [comment]
I thought about adding this, but you can accomplish all of this within the current spec: https://github.com/MineSworn/UltimateArena/wiki/Configuration

**Comment by dmulloy2** [comment]
Added in https://github.com/MineSworn/UltimateArena/commit/24cdac08366eb910e8517523aa9f481fc48eee2f
