### ISSUE TITLE
''Cannot send message'' issue

### ISSUE THREAD

**Issue by Sikatsu** [MineSworn/UltimateArena#165]
I created a FreeForAll Arena, however when I use /ua leave or when the match is finished, I am unable to send messages in the chat including commands. After relogging it works again. Same applies to placing blocks and such. Could you please fix this?

If more information needed, let me know.

**Comment by dmulloy2** [comment]
Fixed in https://github.com/MineSworn/UltimateArena/commit/939c9d13f59cb993746059f4911bc7c4c73d15d9

**Comment by Sikatsu** [comment]
I didn't had overlapping arena's actually

**Comment by dmulloy2** [comment]
Either way that commit should fix the issue.

**Comment by Sikatsu** [comment]
I was on holiday, but the devbuilds seem down at this moment?

**Comment by GarretSidzaka** [comment]
There is something wrong with the server.  I contacted the ISP

**Comment by Sikatsu** [comment]
Thanks, hope it's fixed soon

**Comment by Sikatsu** [comment]
Still not working I see

**Comment by dmulloy2** [comment]
We're currently reimaging it, should be up within the next day or so
