### ISSUE TITLE
The recieved string length is longer than maximum Crash

### ISSUE THREAD

**Issue by Aalscholver** [MineSworn/UltimateArena#167]
Best Dmolloy2.

I created a Mob arena but when I want to play it, you get disconnected from the server with the error: 

Internal exception: io.netty.handler.codec.DecoderException: Received string length longer than maximum allowed (20 > 16)

![image](https://cloud.githubusercontent.com/assets/22894929/20281632/6d53a410-aab1-11e6-8473-5ba2f98c7d48.png)

It doesnt give any reports in the console
I am running this on a Kcauldron 1.7.10 server.
Could you please help me out

Best regards,
Lucas

**Comment by dmulloy2** [comment]
It likely has to do with KCauldron. Are there any errors in console?

**Comment by Aalscholver** [comment]
No, There are no errors in console.... After the countdown you get telleported into the arena and then instantly kicked.

**Comment by dmulloy2** [comment]
What version of UA are you using?

**Comment by Aalscholver** [comment]
Version 3.0

**Comment by dmulloy2** [comment]
It's definitely an issue with either 1.7 or KCauldron. As for what I can do on UA's end, I'm not entirely sure. Does using the latest dev build help?

**Comment by Aalscholver** [comment]
No, the dev build doesnt work either. I think the main cause is definitely at KCauldron. Its a very good plugin, but I think its best to not use the plugin then. 

Thank you for all the help you gave me. I appreciate that.

Lucas
