### ISSUE TITLE
Description is never initialized

### ISSUE THREAD

**Issue by Vervatwala** [MineSworn/UltimateArena#168]
Hello! 
I am using the 3.0 release with a 1.10 server.
Been trying to make some new classes and had a question on how to format the 'potionEffects' option in the yml file. 
The class I was configuring is here: http://pastebin.com/Vkb1tEHu
Basically what I am going for is a Speed 2 potion effect to be given to the class as they spawn in, but I do not know how to format it correctly.

Cheers

**Comment by dmulloy2** [comment]
Guess I forgot to add that to the wiki haha.

The basic format is ````potionEffects: "[effect]:[strength], [effect2]:[strength2]...````

**Comment by Vervatwala** [comment]
Thank you for that! I have another doubt regarding class config again. I am not sure what I am doing wrong but I seem to be getting the writing for the GUI Title and Description wrong, this is what I typed in and did not work: http://pastebin.com/NMKJ33ia also would we use color formats with "&"?

Also just wanted to double check, the Kill Streak part we can write in the "UltimateArena/types/<type>/config.yml" so would this be correct for 2 kills and 4 kills? http://pastebin.com/2rA3Zmkf

Apologies for so many questions, It might be helpful to put a full optioned example of both a areana yml as well as a fully optioned class yml with some ##comments in the wiki.

Thank you for the help agian!

**Comment by Vervatwala** [comment]
How would I format the Title and Description? it would not accept anything I wrote, am I doing something wrong?

**Comment by dmulloy2** [comment]
Are you getting any errors on startup? The description should be a string list.

**Comment by Vervatwala** [comment]
I did, but I hadnt saved the logs. Would it be possible to send over a class yml file with an example of how the Potions, Title and description should be written as? I apologize for such questions Im still getting used to the plugin. 
Or have a fully written out class yml in the wiki? I could try contribute to that once I get familiar with things.

**Comment by dmulloy2** [comment]
https://github.com/MineSworn/UltimateArena/wiki/Classes#example

**Comment by Vervatwala** [comment]
Using your example I made a class like so: http://pastebin.com/c1FLN2sR
however it threw the following errors on server start: http://pastebin.com/Bx9hAv94

**Comment by dmulloy2** [comment]
Huh. It looks like the description variable is never initialized. Must've been left out somewhere. Should be a simple fix.
