### ISSUE TITLE
Overlapping arenas

### ISSUE THREAD

**Issue by angiechin** [MineSworn/UltimateArena#171]
Using latest latest build #839 on Spigot 1.11 server.  Have these few issues, not sure if I don't something wrong but all was working fine until recent few updates:

1) Problem with overlapping arena is still persisting when I create new arena with world edit even though two new position is selected.

2) All created arena gets reset when server restart.

3) I also realised mobs (ua sp are set for the mobs spawning areas. This is for mob arena) are not spawning only the natural mobs are spawning, not sure why.  Previously it was working fine.  

4) Noted if players are in the same area of the arena but not participating in the arena (they are there to spectate), they will die when the arena concludes and those player will loose their items.  Is this something new as it doesn't happened before.  This won't happened if they are not in the arena vicinity.  Is there a way to fix this?

http://pastebin.com/2J2ihy2v

**Comment by dmulloy2** [comment]
1 and 4 sound like intended behavior. 3, 2, and the error appear to be related. Are you actually setting spawns?

**Comment by angiechin** [comment]
The error messages "[UA] These points overlap an existing arena: NiflheimMA!
[15:13:22] [Client thread/INFO]: [CHAT] [UA] This is known to cause problems! Type /ua undo to undo! [15:13:22] [Client thread/INFO]: [CHAT] [UA] Arena points set!" appeared when I tried to create  another new arena  "/create PvP pvp" then selecting two points with world edit. However, I am still able to continue with the rest of the process of creating lobby, Red and Blue team spawn point etc. and etc.  These (the over lapping arena) is probably the reason each time the server restarts daily, all the arena's created gets resets or deleted. 

Anyway, its a fabulous plugin.  We have been using this plugin on the server over almost 2 years I think and have been working well till now.

**Comment by dmulloy2** [comment]
There may be some issues at play with these two commits (https://github.com/MineSworn/UltimateArena/commit/939c9d13f59cb993746059f4911bc7c4c73d15d9, https://github.com/MineSworn/UltimateArena/commit/dc0e110d1177bae62e598b2e887203d3034564b5)

I'll do some testing on my own and let you know.

**Comment by angiechin** [comment]
Sure, thanks.  Btw, I did some further testing.  Down graded to version 3.0 from ultimate arena spigot main page.  I'm able to create arena as usual, no over lapping arena issues, arenas created doesn't reset on restart, mob spawning as per /ua setpoints for mob arena.  Versions from dev. #834 upwards, those issues are present and persisted.  I didn't test #822 & #823, will probably test to see if those gives the same issues.

However, with the version 3.0 when players loses the game (they died) and when arena concluded, they will received this error "Cannot send chat message" when they try to type something in chats.  Those player will need to log out and log in again to the server to send messages hopes to fix this problem.

**Comment by dmulloy2** [comment]
One of the commits I mentioned was meant to fix that issue, so the fix must've broken something else.

**Comment by angiechin** [comment]
Yeah noted that was fixed in build #834 and you are right probably, it broken something else. I'm currently using build #823 for now till you figure it out, I'm clueless in these stuff lol....my players will have to re-log if they get that error "cannot send chat message".

**Comment by dmulloy2** [comment]
Those last two commits _should_ fix the issues you're having

**Comment by angiechin** [comment]
Thanks, updated to latest build #841. Arenas do not get reset when server restarts but issues of over lapping arena still occurring when creating new arenas.
Errors msg:
[19:15:55] [Client thread/INFO]: [CHAT] First position set to (29333.0, 55.0, -11375.0).
[19:16:03] [Client thread/INFO]: [CHAT] Second position set to (29287.0, 109.0, -11309.0) (173195).
[19:16:06] [Client thread/INFO]: [CHAT] [UA] These points overlap existing arenas: PvP, FFA2, Infect, FFACQC, CastleMob, FFA, PvP2, CTF, NiflheimMA!
[19:16:06] [Client thread/INFO]: [CHAT] [UA] This is known to cause problems! Type /ua undo to undo!
[19:16:06] [Client thread/INFO]: [CHAT] [UA] Arena points set!
[19:16:06] [Client thread/INFO]: [CHAT] [UA] Please set 2 points for the lobby using WorldEdit.

**Comment by dmulloy2** [comment]
It would appear that either the bounds of the field are being set incorrectly or the overlap code is not working properly. Are there any issues outside of the message when creating?

**Comment by dmulloy2** [comment]
Is everything working as expected now?

**Comment by angiechin** [comment]
Thank you, it is working as expected with the latest build :)  

Noticed one other issue that if a player who isn't playing the mini-game but in the arena area spectating (not using this command /ua spectate but rather physically there spectating or any player who happens to be inside the boundary of that arena not playing but with game in progress) and when the arena concluded, those players who are not playing will actually get a message that they died, items in their inventory obviously drops as they died and it gets cleared when the arena concluded.  If you get what I meant....

**Comment by dmulloy2** [comment]
I'm not sure if there's a way to fix that, unless I made an option that allowed players to stay. That may cause some other issues though

**Comment by angiechin** [comment]
If there is a way its good otherwise we will cordon off the arena area to prevent non arena player's to go within the arena.  A note thought for those who are setting an area with join signs, do set it outside the arena area otherwise those players will die after the game conclude and lose their survival items.
