### ISSUE TITLE
[API] ArenaSpawnEvent never called

### ISSUE THREAD

**Issue by 2001zhaozhao** [MineSworn/UltimateArena#172]
In the Arena class, the spawn method initializes an ArenaSpawnEvent (and fetches the spawn location from that event), but it is never called.

 I tried to add random spawns to the PVP arena and figured using the event to change the location easier than adding a whole new arena type, but this bug makes me unable to change the spawnpoint of a player during the spawning process.

**Comment by dmulloy2** [comment]
Huh, must've overlooked that
