### ISSUE TITLE
Area reset Question

### ISSUE THREAD

**Issue by CLGREEN94** [MineSworn/UltimateArena#174]
Hello, 

I am playing with the plugin and was wondering if UA has a way of saving and resetting an arena once players have finished in the area? If so how does one do this? if not could this be a feature that could be added? 

Thanks, 
Callum.

**Comment by dmulloy2** [comment]
If by reset you mean restoring the blocks to their original state pregame, then no. It could be added, but I currently don't have the time to do so.
