### ISSUE TITLE
Gametype Idea

### ISSUE THREAD

**Issue by dmulloy2** [MineSworn/UltimateArena#6]
Freeze tag by avrent

two teams. use snowballs to hit other players. when they get hit they get frozen in blocks of ice

allies have to unfreeze with flint and steel (or something like it. fire charge maybe?

objective - freeze the whole other team.

**Comment by Tomgroot** [comment]
+1 - for the frozen players. Maybe is it possible to give them a ice hat when players are frozen. That would look great!

**Comment by dmulloy2** [comment]
This can be added with the API if anyone's interested.
