### ISSUE TITLE
Arena points are incorrectly assigned when WorldEdit is not present

### ISSUE THREAD

**Issue by Foorack** [MineSworn/UltimateArena#90]
As described in title the plugin throws an error when creating an arena.

Server version: CraftBukkit version git-Spigot-eb39b47-0899683 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
Version: 3.0-SNAPSHOT (Build 657)
Error: [UltimateArena] Encountered an exception while executing command setpoint: java.lang.IllegalArgumentException: point2 cannot be null!
Affected classes:
  org.apache.commons.lang.Validate.notNull(Line 192) [spigot-1.8.jar]
  net.dmulloy2.ultimatearena.types.Field.setParam(Line 35) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.types.ArenaZone.initialize(Line 154) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.types.ArenaCreator.complete(Line 136) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.types.ArenaCreator.stepUp(Line 97) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.arenas.mob.MobCreator.setPoint(Line 192) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.UltimateArena.setPoint(Line 1071) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.commands.CmdSetPoint.perform(Line 27) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.commands.Command.execute(Line 126) [UltimateArena.jar]
  net.dmulloy2.ultimatearena.handlers.CommandHandler.onCommand(Line 167) [UltimateArena.jar]
  org.bukkit.command.PluginCommand.execute(Line 44) [spigot-1.8.jar]
  org.bukkit.command.SimpleCommandMap.dispatch(Line 141) [spigot-1.8.jar]
  org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(Line 645) [spigot-1.8.jar]
  java.util.concurrent.Executors$RunnableAdapter.call(Line 511)
  java.util.concurrent.FutureTask.run(Line 266)
  java.lang.Thread.run(Line 745)

**Comment by Foorack** [comment]
I saw your title-change and I had no idea WorldEdit was a requirement to run the plugin. There would be no prob installing it but I haven't seen anywhere where it says it's required.

**Comment by dmulloy2** [comment]
It isn't required, but most servers have it, so UA utilizes it. The issue here is that I never tested the non-WorldEdit point selections.
