### ISSUE TITLE
Class permissions not working

### ISSUE THREAD

**Issue by CadeBrown** [MineSworn/UltimateArena#91]
Hell there! I cannot seem to restrict per-class permissions! this is my supervip.yml file in the /plugins/ultimatearena/classes

>armor:
>  chestplate: IRON_CHESTPLATE, 1, prot:1
>  leggings: IRON_LEGGINGS, 1
>  boots: IRON_BOOTS, 1, prot:1
>tools:
>  '1': DIAMOND_SWORD, 1, sharp:2, fireaspect:1, knockback:1
>  '2': GOLDEN_APPLE, 6
>  '4': 417, 1, silk:7
>  '3': 289, 42
>essentialsKit: ''
>useHelmet: true
>potionEffects: ''
>needsPermission: true
>permissionNode: ultimatearena.class.supervip
>icon: DIAMOND_SWORD, 1, sharp:1

**Comment by CadeBrown** [comment]
I used both permission nodes (for THIS yml file) because the configuration page lists both of them!

**Comment by CadeBrown** [comment]
Right now, anyone gets any class!

**Comment by dmulloy2** [comment]
What version are you using?

**Comment by dmulloy2** [comment]
Closed due to lack of information. Your best bet is to use the latest dev build from here: http://ci.shadowvolt.com/job/UltimateArena
