### ISSUE TITLE
BlacklistedClasses#2

### ISSUE THREAD

**Issue by clergyman48** [MineSworn/UltimateArena#93]
Sorry, but nothing is change.

I removed all signs with classes from game, and changed the configuration of the game infected:

gameTime: 120
lobbyTime: 60
maxDeaths: 2
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: false
cashReward: 100
whitelistedClasses:
(two spaces)- test
blacklistedClasses:
(two spaces)- gunner
rewards:

But when the game starts, players get the default class gunner.
Maybe I need to configure something else?
Thank you for your help

**Comment by dmulloy2** [comment]
Changing the blacklist and whitelist doesn't change the default class. In order to change the default class, set "defaultClass" in the arena data files.
