### ISSUE TITLE
Players can't join from different worlds

### ISSUE THREAD

**Issue by BlackQuests** [MineSworn/UltimateArena#94]
Right now I can't find a possibility to prevent players from joining from different worlds. Our arenas are in world2 and the players can join from either world1 and world2. When they have stuff in their inventory and join a arena from world1 they will lose their items. Is there any way to prevent players from joining from a specific world? I've tried disabling all permissions for the default group, but this doesn't seem to work. Hope there is a solution to this!

**Comment by dmulloy2** [comment]
What version of UltimateArena are you using?

**Comment by dmulloy2** [comment]
Closed due to lack of information.  Your best bet is to try the latest dev build from here: http://ci.shadowvolt.com/job/UltimateArena

**Comment by BlackQuests** [comment]
I'm using v 2.7 sorry for the late response I didn't get a email notification from github for some reason. I'll try the dev build soon and see if that's works. Thanks in advance!
