### ISSUE TITLE
ERROR Could not load Arena Mob: World cannot be null!

### ISSUE THREAD

**Issue by IBICO** [MineSworn/UltimateArena#95]
Same issue with other arena.

08.02 14:05:14 [Server] ERROR Could not load Arena Mob: World cannot be null!
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.handlers.CommandHandler.onCommand(CommandHandler.java:73)
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.commands.UltimateArenaCommand.execute(UltimateArenaCommand.java:92)
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.commands.CmdSetPoint.perform(CmdSetPoint.java:27)
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.UltimateArena.setPoint(UltimateArena.java:1167)
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.creation.MobCreator.setPoint(MobCreator.java:193)
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.creation.ArenaCreator.stepUp(ArenaCreator.java:83)
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.creation.ArenaCreator.complete(ArenaCreator.java:119)
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.types.ArenaZone.save(ArenaZone.java:136)
08.02 14:05:14 [Server] INFO net.dmulloy2.ultimatearena.handlers.FileHandler.save(FileHandler.java:54)
08.02 14:05:14 [Server] INFO Affected classes: 
08.02 14:05:14 [Server] INFO java.lang.NullPointerException: null
08.02 14:05:14 [Server] ERROR Encountered an exception while saving Arena: Mob:
08.02 14:03:58 [Server] INFO [IBICO74: Set own game mode to Creative Mode]
08.02 14:02:27 [Server] INFO IBICO74 has started the creation of Arena: Mob. Type: mob

**Comment by dmulloy2** [comment]
What version of UltimateArena are you using?

**Comment by IBICO** [comment]
2.7

--------
Kenneth Augdal
www.fotonerd.no

**Comment by IBICO** [comment]
The server are 1.8.1 
![screenshot 2015-02-08 22 21 58](https://cloud.githubusercontent.com/assets/10908341/6098503/edf31a4c-afe0-11e4-871c-bd3abc57099f.png)

**Comment by dmulloy2** [comment]
This issue was fixed a while ago, use the latest build from here: http://ci.shadowvolt.com/job/UltimateArena/
