### ISSUE TITLE
Spleef Arena doesn't generate properly

### ISSUE THREAD

**Issue by Jawakotb** [MineSworn/UltimateArena#98]
Dan,
  I have been trying to setup a spleef arena with no success.  I am doing the following:

1) build simple spleef arena (outzone bottom, snow layer above, lobby above that)
2) type "/ua create test spleef"
  "UA asks to set two points for 'Arena' "
3) Using WE wand, I select the upper and lower opposing corners for were the players will be playing spleef. (layer above snow to floor of lobby which is on top)
4) type "/ua sp"
   "UA asks to set two points for 'Lobby' "
5) using WE Wand, I select upper and lower opposing corners for the lobby area
6) type "/ua sp"
  "UA asks to set the 'Lobby spawn' point"
7) standing inside the lobby area where I want the spot to be, then type "/ua sp"
  "UA asks to set the "Spleef" zone"
8) (This is the confusing point) I have to stand on on the same level as the snow layer in one corner and type "/ua sp" cause it will not accept the WE positions.
9) Go to opposite corner of snow layer and type "/ua sp"
   "UA Asks me to enter in the material "
11)  I type "/ua sp 80:0"  for snow
   "UA informs me arena is now ready!

I can join the arena with no issue, it spawns me in the lobby without issue, but then once the match starts, it puts me 70 blocks higher then the spleef floor. (the spleef floor was on 70, but it placed all players at 140 high) at the 140 lvl, there are random 'quartz' blocks and underneath the snow layer is a full layer of quartz.

I am almost certain I am doing something wrong, but the tuts online are not up to date with this version of UA so I am 'winging' it.  

Any assistance would be greatly appreciated.
Thank you.

(PS - I can email screenshots of the arena  "post setup" if needed)

**Comment by dmulloy2** [comment]
Looks like this is an at least somewhat common problem, seems like the same issue in #100
